"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class object_t(object):

    __slots__ = ["timestamp", "name", "detectedObject"]

    __typenames__ = ["int64_t", "string", "boolean"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.name = ""
        """ LCM Type: string """
        self.detectedObject = False
        """ LCM Type: boolean """

    def encode(self):
        buf = BytesIO()
        buf.write(object_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">b", self.detectedObject))

    @staticmethod
    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != object_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return object_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = object_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.detectedObject = bool(struct.unpack('b', buf.read(1))[0])
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if object_t in parents: return 0
        tmphash = (0x3ef2470e535bfeb9) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if object_t._packed_fingerprint is None:
            object_t._packed_fingerprint = struct.pack(">Q", object_t._get_hash_recursive([]))
        return object_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", object_t._get_packed_fingerprint())[0]

