"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class message_t(object):

    __slots__ = ["timestamp", "ID", "name", "detectedObject", "mode"]

    __typenames__ = ["int64_t", "int8_t", "string", "boolean", "int8_t"]

    __dimensions__ = [None, None, None, None, None]

    def __init__(self):
        self.timestamp = 0
        """ LCM Type: int64_t """
        self.ID = 0
        """ LCM Type: int8_t """
        self.name = ""
        """ LCM Type: string """
        self.detectedObject = False
        """ LCM Type: boolean """
        self.mode = 0
        """ LCM Type: int8_t """

    def encode(self):
        buf = BytesIO()
        buf.write(message_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qb", self.timestamp, self.ID))
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">bb", self.detectedObject, self.mode))

    @staticmethod
    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != message_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return message_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = message_t()
        self.timestamp, self.ID = struct.unpack(">qb", buf.read(9))
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.detectedObject = bool(struct.unpack('b', buf.read(1))[0])
        self.mode = struct.unpack(">b", buf.read(1))[0]
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if message_t in parents: return 0
        tmphash = (0x6f094d6a60319c70) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if message_t._packed_fingerprint is None:
            message_t._packed_fingerprint = struct.pack(">Q", message_t._get_hash_recursive([]))
        return message_t._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", message_t._get_packed_fingerprint())[0]

